name: Actualizador ONPE

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Python Setup
        uses: actions/setup-python@v5 # Actualizado a v5
        with:
          python-version: '3.11'

      - name: Librerías
        run: pip install requests

      - name: Scrapping
        run: python scrapper_onpe.py

      - name: Push Changes
        run: |
          git config --global user.name 'Robot ONPE'
          git config --global user.email 'action@github.com'
          git add onpe_data.json
          git commit -m "Auto-update ONPE $(date)" || echo "No changes"
          git push
