name: Actualizador ONPE

on:
  schedule:
    # Se ejecuta cada 30 minutos automáticamente
    - cron: '*/30 * * * *'
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Ajuste de zona horaria para que la fecha sea de Lima/Perú
    env:
      TZ: "America/Lima"

    # Permisos cruciales para que el robot pueda guardar los cambios en el JSON
    permissions:
      contents: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configuración de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalación de Librerías
        run: pip install requests

      - name: Ejecución del Scrapper
        run: python scrapper_onpe.py

      - name: Guardar cambios en el repositorio
        run: |
          git config --global user.name 'Robot ONPE'
          git config --global user.email 'action@github.com'
          git add onpe_data.json
          # Si no hay cambios (datos iguales), no da error
          git commit -m "Auto-update ONPE $(date +'%d/%m/%Y %H:%M:%S')" || echo "No hay cambios nuevos para subir"
          git push
